In [1]:
import numpy as np
import grblas as gb

In [2]:
# Simple graph with 5 triangles
# 0 - 1    5 - 6
# | x |    | /
# 3 - 4 -- 2 - 7
data = np.array([
    [0, 1],
    [0, 3],
    [0, 4],
    [1, 3],
    [1, 4],
    [2, 4],
    [2, 5],
    [2, 6],
    [3, 4],
    [5, 6],
    [6, 7]
])

A = gb.Matrix.from_values(data[:, 0], data[:, 1], [1]*len(data), nrows=8, ncols=8)

# Make A undirected by adding to its transpose
A(gb.binary.plus) << A.T

A

"M_0"          nvals  nrows  ncols  dtype   format
grblas.Matrix     22      8      8  INT64  bitmapr
--------------------------------------------------
   0  1  2  3  4  5  6  7
0     1     1  1
1  1        1  1
2              1  1  1
3  1  1        1
4  1  1  1  1
5        1           1
6        1        1     1
7                    1

In [6]:
# Burkhardt method: num_triangles = sum(sum(A @ A) * A) / 6
triangles = A.mxm(A.T, gb.semiring.plus_pair[
    gb.dtypes.UINT64
    ]).new(mask=A.S)  # Using a (structural) mask is equivalent to the elementwise multiplication step
num_triangles = triangles.reduce_scalar().value // 6
num_triangles

5